### ISSUE TITLE
Doesn't work with iRacing

### ISSUE THREAD

**Issue by thebaz** [tappi287/simmon_gui#1]
I tried every possible exe in the iRacing folder but cannot have this to behave like other steam apps

**Comment by tappi287** [comment]
You can follow these steps for any executable: start the application, wait for it to be fully started, go to your Task Manager > Details, right click the executable that you think belongs to the desired application > Open file location. This will point you to the correct executable.

In the Profiler you simply add that executable with +Add executable to watch. Remember to add another entry and select Deletion as another watch condition.

**Comment by thebaz** [comment]
Thank you! Based on your suggestion I finally found the correct executable. Have BTW a issue:

when closing a game, CrewChief is not quitting until I come back to SimMon... Any suggestion?

**Comment by tappi287** [comment]
"until I come back to SimMon" - hmm, the GUI you see has actually nothing to do with the start/stop of the apps. That is done by the background watcher. There can be a delay up to 8 * 1000 * 6ms, eeeerm 48seconds until commands are issued. Is it maybe just the delay that you observe?

Btw, could you tell me the full path to the iracing executable and do you know the steam appid of that sim? I could add a auto detection for that app then.

**Comment by thebaz** [comment]
Yeah It was the delay...

iRacing not on steam, at least not for me
